version: '3.8'

services:
  web:
    build: ./keyan
    command: gunicorn keyan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./keyan:/usr/src/keyan
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod

    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    # environment:
    #   - POSTGRES_USER=hello_django
    #   - POSTGRES_PASSWORD=hello_django
    #   - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: