# Generated by Django 5.1.2 on 2024-12-15 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organ', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类型编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合同类型',
                'verbose_name_plural': '合同类型',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('title', models.CharField(max_length=200, verbose_name='合同标题')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('content', models.TextField(blank=True, verbose_name='合同内容')),
                ('attachment', models.FileField(blank=True, upload_to='contracts/', verbose_name='附件')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '生效中'), ('completed', '已完成'), ('terminated', '已终止')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_a_contracts', to='organ.organ', verbose_name='甲方')),
                ('party_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_b_contracts', to='organ.organ', verbose_name='乙方')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='关联项目')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.contracttype', verbose_name='合同类型')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('review', '审核'), ('complete', '完成'), ('terminate', '终止')], max_length=20, verbose_name='事件类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contract', verbose_name='合同')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '合同事件',
                'verbose_name_plural': '合同事件',
                'ordering': ['-created_at'],
            },
        ),
    ]
