# Generated by Django 5.1.2 on 2024-12-15 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总预算')),
                ('equipment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='设备费')),
                ('material_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='材料费')),
                ('test_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='测试化验加工费')),
                ('fuel_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='燃料动力费')),
                ('travel_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='差旅费')),
                ('conference_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='会议费')),
                ('international_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='国际合作交流费')),
                ('labor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='劳务费')),
                ('expert_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='专家咨询费')),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='其他费用')),
                ('indirect_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='间接费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_budget', to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目预算',
                'verbose_name_plural': '项目预算',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('date', models.DateField(verbose_name='支出日期')),
                ('category', models.CharField(choices=[('outfund', '外拨经费'), ('overall', '所统筹'), ('other', '其他支出')], max_length=50, verbose_name='支出类型')),
                ('description', models.TextField(verbose_name='说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('payee', models.CharField(max_length=100, verbose_name='收款人')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='银行账号')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户行')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='发票号')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='发票日期')),
                ('attachment', models.FileField(blank=True, upload_to='finance/expense/', verbose_name='附件')),
                ('approve_date', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approve_remarks', models.TextField(blank=True, verbose_name='审批意见')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.budget', verbose_name='预算')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目支出',
                'verbose_name_plural': '项目支出',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', '创建'), ('submit', '提交'), ('approve', '批准'), ('reject', '拒绝'), ('cancel', '取消'), ('modify', '修改')], max_length=50, verbose_name='事件类型')),
                ('description', models.TextField(verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expense', verbose_name='支出')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '支出事件',
                'verbose_name_plural': '支出事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('date', models.DateField(verbose_name='收入日期')),
                ('category', models.CharField(choices=[('contract', '合同收入'), ('support', '配套资金'), ('self', '自筹资金'), ('other', '其他收入')], max_length=50, verbose_name='收入类型')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('attachment', models.FileField(blank=True, upload_to='finance/income/', verbose_name='附件')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目收入',
                'verbose_name_plural': '项目收入',
                'ordering': ['-date'],
            },
        ),
    ]
