# Generated by Django 5.1.2 on 2024-12-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_budget_created_by_alter_budget_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(verbose_name='���入日期'),
        ),
    ]
