version: '3.8'

services:
  web:
    build: .
    container_name: keyan_web
    restart: always
    volumes:
      - ./data:/app/data  # SQLite 数据库文件目录
      - ./static:/app/static  # 静态文件
      - ./media:/app/media  # 媒体文件
    environment:
      - DEBUG=0
      - SECRET_KEY=prfri1324
      - DJANGO_ALLOWED_HOSTS=['*']
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: keyan_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
      - web 