# Generated by Django 5.1.2 on 2024-10-29 08:53

import datetime
import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='项目参与顺序')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.participant', verbose_name='项目参与人')),
            ],
            options={
                'verbose_name': '项目参与',
                'verbose_name_plural': '项目参与',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目编号')),
                ('finance_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='财务编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('project_type', models.CharField(blank=True, choices=[('Ministerial', '部级科研项目'), ('System Position', '国家现代农业产业技术体系岗位专家'), ('National KeyRD', '国家重点研发计划课题'), ('NSFC General ', '国家自然科学基金（面上项目）'), ('National Subtopic', '其他国家级项目（子课题）'), ('Provincial', '省级科研项目'), ('City', '市级科研项目'), ('Academy', '院级科研项目'), ('Institute', '所级基本科研业务费专项项目'), ('Other', '其他项目计划')], max_length=30, null=True, verbose_name='项目类别')),
                ('sign_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='签约日期')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='计划结项日期')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='资金来源')),
                ('contract_fund', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='合同经费(万元)')),
                ('enter_year', models.IntegerField(blank=True, default=project.models.current_year, null=True, verbose_name='登记年度')),
                ('enter_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='登记情况')),
                ('end_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='结项情况')),
                ('doc_transfer', models.CharField(blank=True, max_length=50, null=True, verbose_name='档案移交情况')),
                ('context', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('achievement_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='成果简介')),
                ('status', models.CharField(blank=True, choices=[('Ongoing', '在研'), ('Conclusion', '结题')], default='Ongoing', max_length=10, null=True, verbose_name='项目状态')),
                ('authorize_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.org', verbose_name='委托单位')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='organ.employee', verbose_name='项目负责人')),
                ('participant', models.ManyToManyField(related_name='participants', through='project.Participantion', to='organ.participant', verbose_name='项目参与人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.AddField(
            model_name='participantion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='ProjectDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to=project.models.project_directory_path, verbose_name='文件')),
                ('info', models.CharField(max_length=255, verbose_name='文件信息')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.project', verbose_name='文件所属项目')),
            ],
            options={
                'verbose_name': '项目文档',
                'verbose_name_plural': '项目文档',
            },
        ),
        migrations.AlterUniqueTogether(
            name='participantion',
            unique_together={('project', 'participant')},
        ),
    ]
