# Generated by Django 5.1.2 on 2024-12-15 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organ', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('project_type', models.CharField(choices=[('research', '横向项目'), ('development', '开发项目'), ('consulting', '咨询项目'), ('other', '其他')], max_length=50, verbose_name='项目类型')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预算金额')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('terminated', '已终止')], default='planning', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('lead_organ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_projects', to='organ.organ', verbose_name='主导单位')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to='organ.staff', verbose_name='项目负责人')),
                ('partner_organs', models.ManyToManyField(blank=True, related_name='partner_projects', to='organ.organ', verbose_name='合作单位')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', '项目负责人'), ('leader', '项目组长'), ('coordinator', '项目协调员'), ('researcher', '研究人员'), ('developer', '开发人员'), ('designer', '设计人员'), ('tester', '测试人员'), ('consultant', '顾问'), ('other', '其他')], max_length=50, verbose_name='角色')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在项目中')),
                ('workload', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='工作量（人月）')),
                ('responsibility', models.TextField(blank=True, verbose_name='主要职责')),
                ('performance', models.TextField(blank=True, verbose_name='工作表现')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.staff', verbose_name='人员')),
            ],
            options={
                'verbose_name': '项目参与记录',
                'verbose_name_plural': '项目参与记录',
                'ordering': ['project', 'staff', '-start_date'],
                'unique_together': {('project', 'staff', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(related_name='participated_projects', through='project.ProjectParticipation', to='organ.staff', verbose_name='项目参与人员'),
        ),
    ]
