# Generated by Django 5.1.2 on 2024-12-15 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipation',
            options={'verbose_name': '项目参与', 'verbose_name_plural': '项目参与'},
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipation',
            unique_together={('project', 'staff')},
        ),
        migrations.AddField(
            model_name='project',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='归档原因'),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_archived_projects', to=settings.AUTH_USER_MODEL, verbose_name='归档人'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='是否归档'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预算金额'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(related_name='participated_projects', through='project.ProjectParticipation', to='organ.staff', verbose_name='项目成员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('research', '研究项目'), ('development', '开发项目'), ('consulting', '咨询项目'), ('service', '服务项目'), ('other', '其他项目')], default='research', max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成'), ('suspended', '已暂停'), ('terminated', '已终止')], default='draft', max_length=20, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='responsibility',
            field=models.TextField(blank=True, verbose_name='工作职责'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='role',
            field=models.CharField(choices=[('manager', '项目负责人'), ('leader', '课题负责人'), ('member', '项目成员'), ('consultant', '顾问专家'), ('support', '支持人员')], max_length=20, verbose_name='角色'),
        ),
    ]
